### ISSUE TITLE
"knitr" dependency

### ISSUE THREAD

**Issue by navdeep-G** [hilaryparker/explainr#10] opened 2016-01-03 04:05 UTC
Hi,

Great package. Just tried the ptest() example and I got the following error:

Error in loadNamespace(name) : there is no package called ‘knitr’

Of course, installing "knitr" fixed this, but I figured it would be best to add it to the package dependencies that are loaded when you install explainr().

**Comment by ajschol** [comment] 2016-01-25 04:42
Duplicate of issue #6?

**Closed as completed** 2017-04-18 21:09 UTC
